management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - loggers
        - metrics
spring:
  kafka:
    consumer:
      group-id: sbv2
      auto-offset-reset: earliest
